// Public library API
export { runReview, runSingleAgentReview, filterByConfidence } from "./session/review.js"
export { loadConfig, loadInstructions } from "./config/config.js"
export { discoverRules, formatDiscoveredRules } from "./config/rules.js"
export type { RulesDiscoveryConfig, DiscoveredRule } from "./config/rules.js"
export { gatherStrategyContext } from "./context/strategy.js"
export { loadAgents, filterAgents, excludeAgents } from "./agent/agent.js"
export { getDiff, getAutoDetectedDiff, getDiffStats } from "./tool/diff.js"
export { formatText, formatJson, formatSarif, formatMarkdown } from "./output/format.js"
export type { MarkdownOptions } from "./output/format.js"
export { formatGitHubReview } from "./output/github-review.js"
export type { GitHubReview, GitHubReviewComment } from "./output/github-review.js"
export { loadSuppressRules, shouldSuppress } from "./suppress.js"
export { createBus, bus } from "./bus/index.js"
export { createServer } from "./server/server.js"
export { detectCI, resolveOpencodeBin, inferBaseBranch } from "./env.js"
export { capitalize, slugify, truncate } from "./utils/string.js"

export type { Issue, ReviewResult } from "./types.js"
export type { Config, AgentConfig } from "./config/schema.js"
export type { Agent } from "./agent/agent.js"
export type { ReviewEvents } from "./bus/index.js"
export type { SuppressRule } from "./suppress.js"
